### PR TITLE
feat: Simple refactoring

### PR DESCRIPTION
**Pull request by ajndkr**
This PR performs some minor class refactoring to be more consistent with the BabyAGI example notebook by langchain: https://python.langchain.com/en/latest/use_cases/agents/baby_agi.html

We use `LLMChain` as the base class and `from_llm` classmethod to initialise LLM chains.

### CODE REVIEW

**Comment by hardbyte** [comment]
Doesn't look to run due to the `Scheduler` not implementing everything defined in langchain.

```
    return cls(
TypeError: Can't instantiate abstract class Scheduler with abstract methods _call, input_keys, output_keys
```

**Comment by ajndkr** [comment]
good catch! I haven't gotten around to testing these changes but good to see there are some bugs to fix.

@hardbyte i see you have opened a PR as well. As it's more closer to the current implementation, best to merge yours before mine.

**Comment by giorgiop** [comment]
> good catch! I haven't gotten around to testing these changes but good to see there are some bugs to fix.
> 
> @hardbyte i see you have opened a PR as well. As it's more closer to the current implementation, best to merge yours before mine.

I think @hardbyte rebased that on #1

**Comment by giorgiop** [comment]
LGTM. waiting for rebase

**Comment by hardbyte** [comment]
@ajndkr since this isn't currently running I suggest we merge my PR first, then redo the scheduler/executor refactor on top of main.

**Pull request closed without merging**
